@GitHubApp.Api_HostAddress = http://localhost:5000

### Health Check

GET {{GitHubApp.Api_HostAddress}}/HealthCheck
Accept: application/json

### GitHub Webhook

POST {{GitHubApp.Api_HostAddress}}/api/github/webhooks
Content-Type: application/json

{
  "key": "value",
  "list": [1, 2, 3]
}

###